spring.application.name=GoldSilverApp

spring.datasource.url=jdbc:mysql://localhost:3306/metals_db
spring.datasource.username=root
spring.datasource.password=Mysql@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sign up free at https://metalpriceapi.com ? copy your API key
metal-price-api.base-url: https://api.metalpriceapi.com/v1/latest
metal-price-api.api-key: e10618b7d0ebab7c105c063d162071d5   # free tier: 100 requests/day
metal-price-api.base-currency: INR                 # Indian Rupees
metal.api.base-url=https://api.metalpriceapi.com/v1
metal.api.key=e10618b7d0ebab7c105c063d162071d5

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers

resilience4j.circuitbreaker.instances.metalApi.slidingWindowSize=5
resilience4j.circuitbreaker.instances.metalApi.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.metalApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.metalApi.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.metalApi.permittedNumberOfCallsInHalfOpenState=2

resilience4j.retry.instances.metalApi.maxAttempts=3
resilience4j.retry.instances.metalApi.waitDuration=2s